#!/bin/bash
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     | Version:  v2412
#   \\  /    A nd           | Website:  www.openfoam.org
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# Script to clean the case
#------------------------------------------------------------------------------

# Source OpenFOAM environment
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# Also remove mapped mesh
rm -rf constant/polyMesh

#------------------------------------------------------------------------------